import Sidebar from "./components/Home/Sidebar";
import "./globals.css";
import { Actor, Raleway } from "next/font/google";
const actor = Actor({
  subsets: ["latin"],
  variable: "--actor",
  weight: ["400"],
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--raleway",
  weight: ["400", "100", "200", "300", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${actor.className} ${raleway.className} `}>
    
        <Sidebar>{children}</Sidebar>
      </body>
    </html>
  );
}
